name: language-bh CI

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-22.04, macos-11, macos-12, macos-13 ]
        node-version: [20]
    name: "Build: ${{ matrix.os }} node ${{ matrix.node-version }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Generate grammar JSON files
        run: make grammars
      - name: Run tests
        run: make test
      # Save logs on failure so we can diagnose
      - name: Archive logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Build ${{ matrix.os }} node ${{ matrix.node-version }}
          path: /home/runner/.npm/_logs/
